cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Tung
      last_name: Nguyen
      logged_in: False # Will be managed automatically
      password: admin123456 # Will be hashed automatically
      roles: # Optional
      - admin
oauth2: # Optional
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: # To be filled
    client_secret: # To be filled
    redirect_uri: # URL to redirect to after OAuth2 authentication
  emails:
  - melsby@gmail.com